[project]
name = "kryptografia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=46.0.3",
    "jwt>=1.4.0",
    "mitmproxy>=12.2.1",
    "pyotp>=2.9.0",
]
